# https://cloud.google.com/appengine/docs/standard/nodejs/config/appref

# application: baffle-microsub
runtime: nodejs8

handlers:
# These static file handlers are duplicated in app.js. If you change them here,
# change them there too! Background:
# https://groups.google.com/d/topic/google-appengine/ywNrcyO1CFk/discussion
- url: /public
  static_dir: public
  secure: always

- url: /
  script: auto
  secure: always

- url: /newsblur/.+
  script: auto
  secure: always
